### ISSUE TITLE
Code examples in exercise 10.7 still don't work

### ISSUE THREAD

**Issue by cdsmith** [nomeata/haskell-via-sokoban#4]
Looks like there's been a change to the `Activity` type to not separate step from event handling:

```
data Activity world = Activity
        world
    (Event -> world -> world)
    (world -> Picture)
```

But the code examples afterward are still written against the old type.  For example:

```
resetable :: Activity s -> Activity s
resetable (Activity state0 step handle draw)
  = Activity state0 step handle' draw
  where handle' (KeyPress key) _ | key == "Esc" = state0
        handle' e s = handle e s
```

**Comment by cdsmith** [comment]
I will try to find time to fix this in the next few days if no one gets to it first.

**Comment by nomeata** [comment]
Ah, guess I only fixed the code that is actually run on CodeWorld, but not the inline code…
